# Generated by Django 4.1.7 on 2023-04-26 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=False)),
                ('category', models.CharField(default='fruits', max_length=50)),
                ('color', models.CharField(blank=True, default='', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='Kartik', max_length=50)),
                ('lastname', models.CharField(default='Singhania', max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('agentimage', models.ImageField(null=True, upload_to='uploads/customers/')),
                ('email', models.EmailField(default='karsingh@gmail.com', max_length=50)),
                ('city', models.CharField(default='Koregaon', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('pin', models.CharField(default='000000', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DelivPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='Kartik', max_length=50)),
                ('lastname', models.CharField(default='Singhania', max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('agentimage', models.ImageField(null=True, upload_to='uploads/delivpar/')),
                ('email', models.EmailField(default='karsingh@gmail.com', max_length=50)),
                ('city', models.CharField(default='Koregaon', max_length=50)),
                ('state', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='Kartik', max_length=50)),
                ('lastname', models.CharField(default='Singhania', max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('agentimage', models.ImageField(null=True, upload_to='uploads/invman/')),
                ('email', models.EmailField(default='karsingh@gmail.com', max_length=50)),
                ('city', models.CharField(default='Koregaon', max_length=50)),
                ('state', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=50)),
                ('allowed', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(default='coldr', max_length=60)),
                ('productprice', models.IntegerField(default=300)),
                ('subcategory', models.CharField(default='milk', max_length=50)),
                ('brand', models.CharField(default='PARLEG', max_length=50)),
                ('uom', models.CharField(default='abc', max_length=50)),
                ('offer', models.CharField(default='20%', max_length=10)),
                ('quantity', models.IntegerField(default=10)),
                ('image', models.ImageField(upload_to='uploads/products/')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client_app.category')),
            ],
        ),
    ]
